### ISSUE TITLE
hypertile not shown on nodes

### ISSUE THREAD

**Issue by patientx** [blepping/ComfyUI-bleh#1]
want to try your hypertile node but after installing your nodes from manager and restarting, when I try to add hypertile I only see inspire's version and normal version. Am I missing something ?

NVM, reinstalled via commandline and this time it is shown on the menu.

**Comment by blepping** [comment]
you might have forgotten to refresh the browser, usually it's necessary to restart the server and refresh the browser when installing custom nodes or even updating them (often stuff like node inputs change, or nodes get added/removed).

seems like your issue was solved so i am going to close this. please feel free to open issues or start a discussion if you run into other problems (or even just for ideas/feedback).
